// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwoAvvRLKPlZbQkq5RVg0ktxEdrs5j1UY',
    appId: '1:413722735019:web:d28ff97f58bd20bec062ee',
    messagingSenderId: '413722735019',
    projectId: 'vacc-c08c6',
    authDomain: 'vacc-c08c6.firebaseapp.com',
    storageBucket: 'vacc-c08c6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5pP8byBr87hm72tUu_lmHqcwMNPPry0Y',
    appId: '1:413722735019:android:16a2ca989bb7a9f5c062ee',
    messagingSenderId: '413722735019',
    projectId: 'vacc-c08c6',
    storageBucket: 'vacc-c08c6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnL3j4BPnSoRY7BFOrZ-8BvEICCgGdbto',
    appId: '1:413722735019:ios:38fd1510f942de75c062ee',
    messagingSenderId: '413722735019',
    projectId: 'vacc-c08c6',
    storageBucket: 'vacc-c08c6.firebasestorage.app',
    iosBundleId: 'com.example.vacc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnL3j4BPnSoRY7BFOrZ-8BvEICCgGdbto',
    appId: '1:413722735019:ios:38fd1510f942de75c062ee',
    messagingSenderId: '413722735019',
    projectId: 'vacc-c08c6',
    storageBucket: 'vacc-c08c6.firebasestorage.app',
    iosBundleId: 'com.example.vacc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwoAvvRLKPlZbQkq5RVg0ktxEdrs5j1UY',
    appId: '1:413722735019:web:9bb3045555d1e0afc062ee',
    messagingSenderId: '413722735019',
    projectId: 'vacc-c08c6',
    authDomain: 'vacc-c08c6.firebaseapp.com',
    storageBucket: 'vacc-c08c6.firebasestorage.app',
  );

}